### ISSUE TITLE
gf180mcuC Xschem Setup Bugs

### ISSUE THREAD

**Issue by curtisma** [iic-jku/iic-osic#3]
We're seeing issues with running Xschem with the gf180mcuC process.  It doesn't seem to be working correctly.  It doesn't have the models or PDK setup correctly within xschem.  The $XSCHEM_LIBRARY_PATH is also not setup correctly.  My teammates are also reporting simulation issues.

I start by sourcing the following `.designinit` file in a fresh terminal.

``` bash
#!/bin/bash
export PDK=gf180mcuC
export PDKPATH=$PDK_ROOT/$PDK
export STD_CELL_LIBRARY=gf180mcu_fd_sc_mcu7t5v0
```

Then I start xschem, but it gives me the following incorrect pdk information in the terminal and it can't find the default process schematic as shown in the following error message pop-up.

``` bash
pdk installation: using /foss/pdks
180MCU_MODELS: /foss/pdks/ngspice/models
```

![image](https://user-images.githubusercontent.com/4685385/233838962-ce476425-50bf-424b-8bb6-b14ffae2aed9.png)

This shows that the PDK models and the $XSCHEM_LIBRARY_PATH is not setup correctly.

Doing a diff of the xschemrc from SKY130 and gf180mcuC shows the following as the most significant difference.  I also know several other differences before that which were mostly commented out values but seemed to show the gf180mcuC xschemrc is based off an older version of the xschemrc compared to SKY130.

![image](https://user-images.githubusercontent.com/4685385/233839121-63c61145-00d2-48ef-abaf-bf3652506e12.png)

I'm going to continue debug by updating to the latest version of the container.  Is there a way to check the version number from within it?

**Comment by hpretl** [comment]
> Is there a way to check the version number from within it?

Unfortunately not, but I guess this would be a good idea going forward. I am thinking of an env var like `IIC-OSIC-TOOLS` giving the Docker like `2023.04`.

**Comment by curtisma** [comment]
Sorry I meant to post this in the container repo, but thanks for the reply!  I agree that would be great way to do it.

I'll repost in iic-osic-tools
