### ISSUE TITLE
Error downloading ngspice36

### ISSUE THREAD

**Issue by FraH90** [iic-jku/iic-osic#4]
I'm trying to execute the main script to install this environment for open source IC design.
I'm having this error, seems ngspice-36 is not present on the url specified in the script.

```
>>>> Installing ngspice-36
--2023-05-25 13:35:35--  https://sourceforge.net/projects/ngspice/files/ng-spice-rework/36/ngspice-36.tar.gz
Resolving sourceforge.net (sourceforge.net)... 104.18.10.128, 104.18.11.128
Connecting to sourceforge.net (sourceforge.net)|104.18.10.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-05-25 13:35:35 ERROR 404: Not Found.

gzip: ngspice-36.tar.gz: No such file or directory
tar: ngspice-36.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove 'ngspice-36.tar': No such file or directory
./iic-osic-setup.sh: 227: cd: can't cd to /home/frah/src/ngspice-36
```

Is it a problem of my environment, or something needs to be fixed in the script?

**Comment by FraH90** [comment]
> This script has not been updated in quite a while. Our main development is going into Dockerized solution, hopefully this will suit you. Please look at this whether interesting for you: https://github.com/iic-jku/iic-osic-tools

Ok that's interesting, I'll use the new dockerized solution. 
PS: I'm trying to look for in the readme of https://github.com/iic-jku/iic-osic-tools of an installation procedure.. but I don't see any voice about it. 
Is there some guide for using this environment? How to "install" it and run it?

**Comment by hpretl** [comment]
Good point :-) I have just added a section on top of the README, please take a look at this and let me know if clear enough.

**Comment by FraH90** [comment]
> Good point :-) I have just added a section on top of the README, please take a look at this and let me know if clear enough.

That's perfect, I've been able to "install" it and run it!
I thought some initialization was necessary before launching the first time the vnc interface or the x-server, instead it's only required to launch it for the first time after cloning the repo. 
Thank you! 

(I'll close this issue)
